name: Build
on:
  push:
  pull_request:

jobs:
  game:
    name: Game
    runs-on: ubuntu-latest
    steps:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: mycache
          # If you chose signing key for write access
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - run: nix-shell --run "echo OK"
      - name: Download baserom
        run: curl -L $BASEROM_US_URL -o ver/us/baserom.z64
        env:
          BASEROM_US_URL: ${{ secrets.BASEROM_US_URL }}
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
      - name: Configure
        run: ./configure
      - uses: root-project/gcc-problem-matcher-improved@v0.0.1-alpha.1
      - name: Build
        run: ninja ver/us/build/papermario.bps
      - name: Upload patch as artifact
        uses: actions/upload-artifact@v4
        with:
          name: papermario.bps
          path: ver/us/build/papermario.bps
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    needs: game
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: papermario.bps
          path: papermario.bps
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: Development build
          files: papermario.bps
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: game
    if: github.ref == 'refs/tags/v*'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: papermario.bps
          path: papermario.bps
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: papermario.bps
